import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, Clock3, FileText, Loader2, Mail, Send, XCircle } from "lucide-react";
import { useLocation } from "wouter";

const label: Record<string, string> = { review: "Review pending", sending: "Sending", completed: "Completed", completed_with_errors: "Completed with issues", failed: "Needs attention" };

function HistoryContent() {
  const [, navigate] = useLocation();
  const history = trpc.mailer.history.useQuery();
  if (history.isLoading) return <div className="grid min-h-[60vh] place-items-center"><Loader2 className="h-6 w-6 animate-spin text-[#b35e45]" /></div>;
  return <div className="mx-auto max-w-5xl pb-12"><header className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[.18em] text-[#aa5d46]">Delivery log</p><h1 className="font-serif text-4xl tracking-[-.04em] text-[#2d251f] sm:text-5xl">Send history.</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">A transparent record of every prepared and completed outreach session.</p></div><Button className="bg-[#b35e45] text-white hover:bg-[#994c37]" onClick={() => navigate("/")}><Send className="mr-2 h-4 w-4" />New email</Button></header>
    {!history.data?.length ? <div className="rounded-2xl border border-dashed border-[#dfc7bb] bg-[#fffaf7] p-12 text-center"><Clock3 className="mx-auto h-7 w-7 text-[#b5634a]" /><h2 className="mt-4 text-lg font-semibold text-[#3a2a23]">No sends yet</h2><p className="mt-2 text-sm text-muted-foreground">Your reviewed send sessions will appear here.</p></div> : <div className="space-y-4">{history.data.map(session => { const sent = session.recipients.filter(recipient => recipient.status === "sent").length; const failed = session.recipients.filter(recipient => recipient.status === "failed").length; const good = session.status === "completed"; return <article key={session.id} className="rounded-2xl border border-[#eadbd1] bg-[#fffdfb] p-5 shadow-[0_16px_42px_-32px_rgba(69,42,30,.5)]"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex items-center gap-2"><span className={`grid h-8 w-8 place-items-center rounded-lg ${good ? "bg-emerald-50 text-emerald-600" : failed ? "bg-[#fff0eb] text-[#b6533c]" : "bg-[#fff4de] text-[#aa7725]"}`}>{good ? <CheckCircle2 className="h-4 w-4" /> : failed ? <XCircle className="h-4 w-4" /> : <Clock3 className="h-4 w-4" />}</span><span className="text-sm font-semibold text-[#3a2a23]">{label[session.status]}</span></div><h2 className="mt-4 truncate text-base font-semibold text-[#3a2a23]">{session.subject}</h2><p className="mt-1 flex items-center gap-2 text-xs text-muted-foreground"><FileText className="h-3.5 w-3.5" />{session.attachmentName}</p></div><div className="text-left text-xs text-muted-foreground sm:text-right"><p>{new Date(session.finishedAt ?? session.createdAt).toLocaleString()}</p><p className="mt-2"><strong className="text-[#3a2a23]">{sent}</strong> sent · <strong className="text-[#3a2a23]">{failed}</strong> failed · {session.recipients.length} total</p></div></div><div className="mt-5 flex flex-wrap gap-2 border-t border-[#f0e5de] pt-4">{session.recipients.map(recipient => <span key={recipient.id} className={`rounded-full px-2.5 py-1 text-xs ${recipient.status === "sent" ? "bg-emerald-50 text-emerald-700" : recipient.status === "failed" ? "bg-[#fff0eb] text-[#b6533c]" : "bg-[#f6f2ef] text-[#75645c]"}`}>{recipient.email}</span>)}</div></article>; })}</div>}</div>;
}

export default function History() { return <DashboardLayout><HistoryContent /></DashboardLayout>; }
